name: Job Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  job_fetcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run job fetcher script
        run: |
          echo "Running job fetcher with auth token"
          python job_fetcher.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push job details
        run: |
          git config --global user.name "nikbckm"
          git config --global user.email "nikbckm@users.noreply.github.com"
          git add job_details.csv
          git commit -m "Updated job details" || echo "No changes to commit"
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/nikbckm/arbeitsamt-data-job-fetcher.git HEAD:main
