name: Job Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day (UTC)
  workflow_dispatch:     # Allows manual trigger

jobs:
  backup-and-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests  # Requests is the only external dependency

    - name: Run the job fetcher script
      run: |
        python job_fetcher.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add job_details.csv job_details_backups/*
        git commit -m "Update job details CSV and backup [automated]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nikbckm/arbeitsamt-data-job-fetcher.git
