name: Job Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the job fetcher every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  job_fetcher:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Set up GitHub token for authentication (use secret)
      - name: Set up GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.job-fetcher-token }}
        run: |
          echo "Using GitHub token for authentication"

      # Run the job fetcher script
      - name: Run job fetcher script
        env:
          GITHUB_TOKEN: ${{ secrets.job-fetcher-token }}
        run: |
          python job_fetcher.py  # Run the script that fetches and updates the job details CSV

      # Commit and push job details to repository
      - name: Commit and push job details to repository
        run: |
          git config --global user.name "nikbckm"
          git config --global user.email "nikbckm@users.noreply.github.com"
          git add job_details.csv
          git commit -m "Updated job details"
          git push origin main
